#
# Note: the  ENV values of
# ANSIBLE_HASHI_VAULT_NAMESPACE
# ANSIBLE_HASHI_VAULT_ADDR
# ANSIBLE_HASHI_ROLE_ID
# ANSIBLE_HASHI_VAULT_SECRET_ID
# ANSIBLE_HASHI_VAULT_AUTH_METHOD
# must be defined

- name: Get All secrets for drone from VAULT
  ansible.builtin.set_fact:
    drone_vault_secrets: "{{ lookup('community.general.hashi_vault', 'secret=secret/data/CI/drone') }}"
  tags:
    - vault

- name: Dereference All the secrets that we need
  set_fact:
    drone_rpc_secret: "{{ drone_vault_secrets['drone_rpc_secret'] }}"
    drone_github_client_id: "{{ drone_vault_secrets['drone_github_client_id'] }}"
    drone_github_client_secret: "{{ drone_vault_secrets['drone_github_client_secret'] }}"
    drone_secret_plugin: "{{ drone_vault_secrets['drone_secret_plugin'] }}"
