---
- name: "Create systemd Template file"
  template:
    src: "drone-plugin-vault-systemd.service.j2"
    dest: "/etc/systemd/system/drone-plugin-vault-systemd.service"
  register: drone_plugin_vault_systemd_config
  notify:
    - "plugin vault systemd restart"
  tags:
    - configuration

- name: "Enable and start the drone plugin vault service"
  systemd:
    name: drone-plugin-vault-systemd
    state: started
    enabled: True
    daemon_reload: yes
