---

  ## fix me: there is a flaw in the logic with folder.changed and if defined.
  # on the first run if something doesn't complete, the folder will never go to changed again.
- name: run drone server with sqlite database
  docker_container:
    name: drone-server
    image: "drone/drone:{{ drone_version }}"
    state: started
    restart_policy: always
    ports:
      - "{{ drone_host_port }}:80"
    volumes:
      - "{{ drone_sqlite_dir }}:/data"
    env_file: /etc/drone/drone-server.env
  when: ((drone_server_config is defined and drone_server_config.changed) or
        (drone_sqlite_folder is defined and drone_sqlite_folder.changed)) and
        (drone_database_driver == "sqlite") and (drone_enable_systemd == "false" )
  tags:
    - drone-server
    - skip_ansible_lint

- name: run drone server with postgres or mysql database
  docker_container:
    name: drone-server
    image: "drone/drone:{{ drone_version }}"
    state: started
    restart_policy: always
    ports:
      - "{{ drone_host_port }}:80"
    links:
      - "{{ drone_database_driver }}"
    volumes:
      - "{{ drone_sqlite_dir }}:/data"
    env_file: /etc/drone/drone-server.env
  when: ((drone_server_config is defined and drone_server_config.changed) or
        (drone_postgres_data_dir is defined and drone_postgres_data_dir.changed)) and
        (drone_database_driver != "sqlite") and (drone_enable_systemd == "false")
  tags:
    - drone-server
    - skip_ansible_lint