---
# this include file setups a complete configuation
- include_vars: home_lab_reverse_proxy_letsencrypt.yml
  when: drone_home_lab_reverse_proxy_letsencrypt | default(false) | bool == true

- include: approle-secrets.yml
  when: drone_home_lab_reverse_proxy_letsencrypt | default(false) | bool == true

- include: setup.yml

- include: drone-plugin-vault.yml
- include: drone-plugin-vault-systemd.yml
#
#  If we are using vault
#
- include: vault.yml
  when:
    - drone_get_secrets_from_vault |default(False) | bool == True
#
#  If we are using vault
#
- include: vault-variables.yml
  when:
    - drone_get_secrets_from_vault |default(false) | bool == true

- include: drone-database.yml
  when: drone_database_driver != "sqlite"

- include: drone-server.yml

#
# When install certs is enabled
#

- include: install-certs-local.yml
  when:
    - drone_certs_from_vault |default(false) | bool == false
    - drone_install_certs |default(false) | bool == true

- include: install-certs-vault.yml
  when:
    - drone_certs_from_vault |default(false) | bool == true

  #  - drone_install_certs |default(false) | bool == true
- include: drone-runner.yml
  when: drone_runner_enable | default(false) | bool == true

- include: drone-runner-systemd.yml
  when: drone_runner_enable | default(false) | bool == true

- include: drone-server-systemd.yml
