---
# handlers file for ansible-drone
- name: "server systemd restart"
  systemd:
    name: drone-server-systemd
    state: restarted
    enabled: True
    daemon_reload: yes
  when: drone_enable_systemd == "true"

# handlers file for ansible-drone
- name: "runner systemd restart"
  systemd:
    name: drone-runner-systemd
    state: restarted
    enabled: True
    daemon_reload: yes
  when: drone_enable_systemd == "true"

# handlers file for ansible-drone
- name: "plugin vault systemd restart"
  systemd:
    name: drone-plugin-vault-systemd
    state: restarted
    enabled: True
    daemon_reload: yes
  when: drone_enable_systemd == "true"
